import './Home.scss'

export const Home = () => {
  return (
    <div className='home'>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
      <h2>HOME</h2>
    
    </div>
  )
}
